# Generated by Django 5.2.3 on 2025-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herocarouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_title', models.CharField(help_text='e.g., CEO, Manager, Founder', max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('testimonial_text', models.TextField(help_text='The testimonial content')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
