# Generated by Django 5.2.3 on 2025-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonialcarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.TextField(blank=True, help_text='Base64 encoded industry image'),
        ),
    ]
