# Generated by Django 5.2.3 on 2025-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_industry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.TextField(blank=True, help_text='Base64 encoded site logo'),
        ),
    ]
