# Generated by Django 5.2.3 on 2025-08-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocarouselimage',
            name='hero_subtitle',
            field=models.TextField(default='Streamline your B2B trading with our multi-vendor platform. Find verified suppliers, secure payments, and industry-focused solutions.', help_text='Hero subtitle/description text'),
        ),
        migrations.AddField(
            model_name='herocarouselimage',
            name='hero_title',
            field=models.CharField(default='Connect in Metal, Wood, Plastic, Machineries, Technology', help_text='Main hero title text', max_length=300),
        ),
    ]
