# Generated by Django 5.2.3 on 2025-08-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_herocarouselimage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers first)'),
        ),
    ]
