# Generated by Django 5.2.3 on 2025-08-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_industry_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Industries'},
        ),
    ]
