# Generated by Django 5.2.3 on 2025-09-15 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_industry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('29.00'), help_text='One-time annual registration fee (not a subscription). Use admin to change.', max_digits=10),
        ),
    ]
