# Generated by Django 5.2.4 on 2025-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('business_buyer', 'Business Buyer'), ('consumer_buyer', 'Consumer Buyer')], default='vendor', help_text='Are you registering as a vendor or buyer?', max_length=20),
        ),
    ]
