# Generated by Django 5.2.3 on 2025-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='role',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_types',
            field=models.JSONField(blank=True, default=list, help_text='List of company types'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='cr_number',
            field=models.CharField(blank=True, help_text='CR Number / VAT / Tax ID', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='other_company_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='other_sector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.JSONField(blank=True, default=list, help_text='List of business sectors'),
        ),
    ]
