# Generated by Django 5.2.3 on 2025-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_company_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_city',
            field=models.CharField(blank=True, default='Dubai', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_country',
            field=models.CharField(blank=True, default='United Arab Emirates', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_country_code',
            field=models.CharField(blank=True, default='AE', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_postal_code',
            field=models.CharField(blank=True, default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_state',
            field=models.CharField(blank=True, default='Dubai', max_length=100),
        ),
    ]
