"""
Django settings for m2w_platform project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decimal import Decimal
from decouple import config 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-l8w8l-6zlas3h%xj!2-n*_al**=pkw+&oed+x*(=130rn8pivr')  # fallback for local dev

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False')
# DEBUG = 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
# ALLOWED_HOSTS = ["*"]  # Allow all hosts (insecure for production)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'core',
    'accounts',
    'products',
    'messaging',
    'payments',  # ← ADD THIS LINE
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'm2w_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'm2w_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (even though using base64, keep for future)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024   # 50MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000             # Increase field limit

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration (for development)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


# Security Settings
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Content Security Policy
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Jazzmin config
JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "MWPUAE Admin Panel",
    "site_header": "MWPUAE Platform Admin",
    "site_brand": "MWPUAE Platform",

    # 👇 THIS IS THE IMPORTANT PART
    "site_logo": "images/Metal Wood Plastic Technology FZC LLC_icon.svg",          # sidebar + top-left logo
    "login_logo": "images/Metal Wood Plastic Technology FZC LLC_icon.svg",         # login page logo (optional)
    "site_logo_classes": "img-circle",       # optional styling

    "show_developer": False,
    "copyright": "© 2025 MWPUAE Platform",

    # Theme
    "theme": "darkly",
    "dark_mode_theme": "cyborg",

    # UI
    "show_ui_builder": True,

    # Layout
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
    ],
    "order_with_respect_to": ["auth", "core"],
    "custom_css": None,
    "custom_js": None,
    # …and dozens more. See full list:
    # https://github.com/farridav/django-jazzmin#settings
}

JAZZMIN_SETTINGS["show_ui_builder"] = True


# In your settings.py or as a site setting
# DEFAULT_MONTHLY_FEE = 30  # $30/month for everyone
DEFAULT_REGISTRATION_FEE = Decimal('29.00')  # One-time annual registration

# ============================================
# N-Genius Payment Configuration
# ============================================

# IMPORTANT:
# Use the correct N-Genius Base URL for your environment.
# These are critical for backend authentication (identity) and creating orders:
#
#   Sandbox (UAT):    https://api-gateway.sandbox.ngenius-payments.com
#   Production (Live): https://api-gateway.ngenius-payments.com
#
# Set NGENIUS_BASE_URL in your .env or environment config accordingly.

NGENIUS_BASE_URL = config(
    'NGENIUS_BASE_URL',
    default='https://api-gateway.sandbox.ngenius-payments.com'
)


NGENIUS_OUTLET_REF = config('NGENIUS_OUTLET_REF')
NGENIUS_HOSTED_SESSION_API_KEY = config('NGENIUS_HOSTED_SESSION_API_KEY')  # For frontend SDK payments
NGENIUS_SERVICE_ACCOUNT_API_KEY = config('NGENIUS_SERVICE_ACCOUNT_API_KEY')  # For backend authentication

# Multi-Currency Pricing (MCP)
NGENIUS_MCP_ENABLED = config('NGENIUS_MCP_ENABLED', cast=bool, default=True)

# Payment session and webhook settings
PAYMENT_WEBHOOK_TIMEOUT = 30   # seconds
PAYMENT_SESSION_EXPIRY = 3600  # seconds (1 hour)

# Logging for payments (log file will be created in BASE_DIR/logs/)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'payments_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'payments.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'payments': {
            'handlers': ['payments_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ============================================
# CSRF CONFIGURATION FOR TUNNELING
# ============================================

# For local development with ngrok/pinggy tunnels
# Add your tunnel domain here
CSRF_TRUSTED_ORIGINS = [
    # Local development
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    
    # Ngrok tunnels (add your actual ngrok URL)
    'https://abcd1234.ngrok.io',  # Replace with your ngrok URL
    'https://*.ngrok.io',  # Wildcard for all ngrok subdomains
    
    # Pinggy tunnels (add your actual pinggy URL)
    'https://ejrfr-122-164-82-206.a.free.pinggy.link',  # Your current pinggy URL
    'https://*.free.pinggy.link',  # Wildcard for all pinggy subdomains
    # Production (add when you go live)
    'https://mwpuae.ae',
    'https://www.mwpuae.ae',
]

# Also ensure CSRF cookie settings are correct
CSRF_COOKIE_SECURE = False  # Set to True only in HTTPS production
CSRF_COOKIE_HTTPONLY = False  # JavaScript needs to read CSRF token in forms
