# Generated by Django 5.2.4 on 2025-07-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinquiry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productinquiry',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['industry', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_status_28f1d7_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='featured',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending Approval'), ('sold', 'Sold'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-created_at'], name='products_pr_status_8ee08e_idx'),
        ),
        migrations.DeleteModel(
            name='ProductInquiry',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
